header:
  version: 1

machine: cm5-mi450-linnie
distro: 
target: 

repos:
  bitbake:
    url: 
    branch: 
    # or
    commit:
    path:
    layers:

  openembedded-core:
    url:
    branch:
    path:
    layers:
      meta:
  meta-raspberrypi:
      commit: 255500dd9f6a01a3445ac491d1abc401801e3bad
  meta-rauc:
      commit: 4cb7c47686d5dec9bacae6110f1bcaac57568691

  meta-cm5:
    path: meta-cm5
  meta-linnie:
    path: meta-linnie